services:
  web:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - redis
    environment:
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: America/Toronto
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
